
services:
  postgres:
    image: postgres:latest
    container_name: movieapp-postgres
    environment:
      POSTGRES_DB: movieapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movieapp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: movieapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@movieapp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - movieapp-network

volumes:
  postgres_data:

networks:
  movieapp-network:
    driver: bridge



