### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/trending-movies
Accept: application/json

###
PUT http://localhost:8080/api/trending-movies
Content-Type: application/json

{
  "searchTerm": "Incept",
  "movieId": 27205,
  "title": "Inception",
  "posterUrl": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg"
}

###
PUT http://localhost:8080/api/trending-movies
Content-Type: application/json

{
"searchTerm": "action",
"movieId": 299536,
"title": "Avengers: Infinity War",
"posterUrl": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg"
}