###
POST http://localhost:8080/api/saved-movies
Content-Type: application/json
Authorization: Bearer token

{
  "id": 27205,
  "title": "test title",
  "poster_path": "https://placehold.co/600x400/1a1a1a/ffffff.png",
  "release_date": "2012-02-01",
  "vote_average": 8.5,
  "original_language": "en"
}

###
GET http://localhost:8080/api/saved-movies
Authorization: Bearer token

###
GET http://localhost:8080/api/saved-movies/12
Content-Type: application/json
Authorization: Bearer token

###
DELETE http://localhost:8080/api/saved-movies/27205
Authorization: Bearer token