###
GET http://localhost:8080/api/trending-movies
Accept: application/json

###
PUT http://localhost:8080/api/trending-movies
Content-Type: application/json

{
  "searchTerm": "Star Wars",
  "movieId": 680,
  "title": "Star Wars: Revenge of the Sith",
  "posterUrl": "https://placehold.co/400x600/1a1a1a/ffffff.png"
}

###
PUT http://localhost:8080/api/trending-movies
Content-Type: application/json

{
"searchTerm": "avengers",
"movieId": 299536,
"title": "Avengers: Infinity War",
"posterUrl": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg"
}




